# Generated by Django 3.2 on 2021-05-18 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainHorizontalBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Элемент горизонтального меню',
                'verbose_name_plural': 'Элементы горизонтального меню',
            },
        ),
        migrations.CreateModel(
            name='VertiсalBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Элемент вертикального меню',
                'verbose_name_plural': 'Элементы вертикального меню',
            },
        ),
        migrations.CreateModel(
            name='SubHorizontalBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('mainhorizontalbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidebar.mainhorizontalbar')),
            ],
            options={
                'verbose_name': 'Под элемент горизонтального меню',
                'verbose_name_plural': 'Под элементы горизонтального меню',
            },
        ),
    ]
