# Generated by Django 3.2 on 2021-05-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidebar', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainhorizontalbar',
            options={'ordering': ('position',), 'verbose_name': 'Элемент горизонтального меню', 'verbose_name_plural': 'Элементы горизонтального меню'},
        ),
        migrations.AlterModelOptions(
            name='vertiсalbar',
            options={'ordering': ('position',), 'verbose_name': 'Элемент вертикального меню', 'verbose_name_plural': 'Элементы вертикального меню'},
        ),
        migrations.AddField(
            model_name='mainhorizontalbar',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='subhorizontalbar',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='vertiсalbar',
            name='position',
            field=models.PositiveIntegerField(default=1, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='mainhorizontalbar',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
