# Generated by Django 3.1.7 on 2021-04-15 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование учреждения')),
                ('slug', models.SlugField(unique=True)),
                ('full_name', models.TextField(blank=True, null=True, verbose_name='Полное наименование учреждения')),
            ],
        ),
        migrations.CreateModel(
            name='Models_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование РС')),
                ('type_rs', models.CharField(choices=[('nosim', 'Носимая'), ('mobile', 'Мобильная'), ('stationary', 'Стационарная')], max_length=100, verbose_name='Тип РС')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_number', models.CharField(max_length=30, verbose_name='Инвентарный номер')),
                ('serial_number', models.CharField(max_length=30, verbose_name='Серийный номер')),
                ('category', models.CharField(choices=[('first', 'Первая'), ('second', 'Вторая'), ('third', 'Третья'), ('fourth', 'Четвертая')], default='second', max_length=10, verbose_name='Категория РС')),
                ('production_year', models.CharField(help_text='Формат ввода <em>ГГГГ</em>', max_length=4, verbose_name='Год выпуска РС')),
                ('date_to_work', models.DateField(verbose_name='Дата ввода в эксплуатацию')),
                ('order', models.CharField(help_text='формат ввода <em>№ XX от ДД.MM.ГГГГ</em>', max_length=100, verbose_name='Приказ о закреплении')),
                ('place_of_opeation', models.CharField(max_length=250, verbose_name='Место эксплуатации оборудования')),
                ('lifetime', models.CharField(max_length=100, verbose_name='Срок эксплуатации')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_radiostation.institutions', verbose_name='Учреждение')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_radiostation.models_name', verbose_name='Наименование РС')),
            ],
        ),
    ]
