# Generated by Django 3.1.7 on 2021-04-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': 'Радиостанция', 'verbose_name_plural': 'Радиостанции'},
        ),
        migrations.AlterModelOptions(
            name='institutions',
            options={'verbose_name': 'Учреждение', 'verbose_name_plural': 'Учреждения'},
        ),
        migrations.AlterModelOptions(
            name='models_name',
            options={'verbose_name': 'Модель радиостанции', 'verbose_name_plural': 'Модели радиостанций'},
        ),
        migrations.RemoveField(
            model_name='institutions',
            name='full_name',
        ),
        migrations.AddField(
            model_name='base',
            name='comment',
            field=models.CharField(max_length=50, null=True, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='base',
            name='place_of_opeation',
            field=models.CharField(choices=[('security', 'Применяется в организации связи подразделений охраны и конвоирования'), ('sefety', 'Применяется в организации связи подразделений режима и надзора (безопасности)'), ('lzu', 'Применяется в организации связи на лесозаготовительных участках'), ('op4', 'Применяется в организации связи службы ОПЧ'), ('warehouse', 'Хранится на складе учреждения'), ('gbr', 'Группа быстрого реагирования'), ('other', 'Иное не включенное в другие группы')], max_length=250, verbose_name='Место эксплуатации оборудования'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='name',
            field=models.CharField(help_text='Формат ввода ИК/УК/КП/СИЗО/ЛИУ-ХХ', max_length=255, verbose_name='Краткое наименование учреждения'),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL учреждения'),
        ),
    ]
