# Generated by Django 3.1.7 on 2021-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0002_auto_20210419_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_rs/', verbose_name='Фотография РС'),
        ),
        migrations.AlterField(
            model_name='base',
            name='comment',
            field=models.CharField(blank=True, max_length=50, verbose_name='Комментарии'),
        ),
        migrations.AlterField(
            model_name='models_name',
            name='type_rs',
            field=models.CharField(choices=[('Носимая', 'Носимая'), ('Мобильная', 'Мобильная'), ('Стационарная', 'Стационарная')], max_length=100, verbose_name='Тип РС'),
        ),
    ]
