# Generated by Django 3.1.7 on 2021-04-21 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0003_auto_20210421_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos_rs/', verbose_name='Фотография РС'),
        ),
    ]
