# Generated by Django 3.2 on 2021-04-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0004_auto_20210421_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'ordering': ['institution', 'category', 'model_name', 'serial_number'], 'verbose_name': 'Радиостанция', 'verbose_name_plural': 'Радиостанции'},
        ),
        migrations.AlterModelOptions(
            name='institutions',
            options={'ordering': ['name'], 'verbose_name': 'Учреждение', 'verbose_name_plural': 'Учреждения'},
        ),
        migrations.AlterModelOptions(
            name='models_name',
            options={'ordering': ['type_rs', 'name'], 'verbose_name': 'Модель радиостанции', 'verbose_name_plural': 'Модели радиостанций'},
        ),
        migrations.AlterField(
            model_name='base',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos_rs/', verbose_name='Фотография РС'),
        ),
    ]
