# Generated by Django 3.2 on 2021-04-21 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0005_auto_20210421_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_radiostation.institutions', verbose_name='Учреждение'),
        ),
        migrations.AlterField(
            model_name='base',
            name='model_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_radiostation.models_name', verbose_name='Наименование РС'),
        ),
        migrations.AlterField(
            model_name='base',
            name='serial_number',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Серийный номер'),
        ),
    ]
