# Generated by Django 3.2 on 2021-04-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0007_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
