# Generated by Django 3.2 on 2021-05-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0008_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base',
            name='category',
            field=models.CharField(choices=[[1, 'Первая'], [2, 'Вторая'], [3, 'Третья'], [4, 'Четвертая']], default='second', max_length=10, verbose_name='Категория РС'),
        ),
    ]
