# Generated by Django 3.2 on 2021-05-06 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0012_rename_base_base_rs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rs',
            name='lifetime',
            field=models.CharField(blank=True, max_length=100, verbose_name='Срок эксплуатации'),
        ),
    ]
