# Generated by Django 3.2 on 2021-05-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0013_alter_base_rs_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rs',
            name='category',
            field=models.CharField(choices=[('first', 'Первая'), ('second', 'Вторая'), ('third', 'Третья'), ('fourth', 'Четвертая')], default='first', max_length=10, verbose_name='Категория РС'),
        ),
    ]
