# Generated by Django 3.2 on 2021-05-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0014_alter_base_rs_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL учреждения'),
        ),
    ]
