# Generated by Django 3.2 on 2021-05-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0015_alter_institutions_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base_rs',
            options={'ordering': ['institution'], 'verbose_name': 'Радиостанция', 'verbose_name_plural': 'Радиостанции'},
        ),
        migrations.AlterField(
            model_name='base_rs',
            name='lifetime',
            field=models.CharField(blank=True, default='payment_lifetime', max_length=100, verbose_name='Срок эксплуатации'),
        ),
    ]
