# Generated by Django 3.2 on 2021-05-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0017_alter_base_rs_lifetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rs',
            name='date_to_work',
            field=models.DateTimeField(verbose_name='Дата ввода в эксплуатацию'),
        ),
    ]
