# Generated by Django 3.2 on 2021-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0019_alter_base_rs_date_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rs',
            name='date_to_work',
            field=models.DateTimeField(verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AlterField(
            model_name='base_rs',
            name='lifetime',
            field=models.CharField(blank=True, max_length=250, verbose_name='Срок эксплуатации'),
        ),
    ]
