# Generated by Django 3.2 on 2021-05-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0020_auto_20210507_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='base_rs',
            name='date_to_work',
            field=models.DateField(verbose_name='Дата ввода в эксплуатацию'),
        ),
    ]
