# Generated by Django 3.2 on 2021-05-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0023_base_rs_lifetime_int'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='base_rs',
            name='lifetime_int',
        ),
    ]
