# Generated by Django 3.2 on 2021-05-13 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_radiostation', '0024_remove_base_rs_lifetime_int'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Base_rs',
            new_name='Radiostations',
        ),
    ]
