# Generated by Django 3.2 on 2021-04-30 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата ГК')),
                ('number', models.CharField(max_length=10, verbose_name='Номер ГК')),
                ('upload', models.FileField(upload_to='GK/%title/', verbose_name='Файл')),
                ('post', models.CharField(max_length=50, verbose_name='Поставщик')),
            ],
        ),
    ]
