# Generated by Django 3.2 on 2021-04-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_regulations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regulations',
            options={'verbose_name': 'Государственный контракт', 'verbose_name_plural': 'Государственные контракты'},
        ),
        migrations.AlterField(
            model_name='regulations',
            name='upload',
            field=models.FileField(upload_to='GK/', verbose_name='Pdf'),
        ),
    ]
