# Generated by Django 3.2 on 2021-04-30 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210430_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='upload',
            field=models.FileField(upload_to='GK/<django.db.models.fields.CharField>.pdf', verbose_name='Pdf'),
        ),
    ]
