# Generated by Django 3.2 on 2021-04-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_regulations_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='upload',
            field=models.FileField(upload_to='GK/gk_ot_<django.db.models.fields.DateField>_<django.db.models.fields.CharField>.pdf', verbose_name='Pdf'),
        ),
    ]
