# Generated by Django 3.2 on 2021-04-30 05:48

import citov.apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_regulations_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='upload',
            field=models.FileField(upload_to=citov.apps.news.models.content_file_name, verbose_name='Pdf'),
        ),
    ]
