# Generated by Django 3.2 on 2021-05-04 06:37

import citov.apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_regulations_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата Приказа')),
                ('number', models.CharField(max_length=10, verbose_name='Номер Приказа')),
                ('upload', models.FileField(upload_to=citov.apps.news.models.content_GK, verbose_name='Pdf')),
            ],
            options={
                'verbose_name': 'Приказ',
                'verbose_name_plural': 'Приказы',
            },
        ),
    ]
