# Generated by Django 3.2 on 2021-05-04 06:50

import citov.apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='upload',
            field=models.FileField(upload_to=citov.apps.news.models.content_Prikaz, verbose_name='Pdf'),
        ),
    ]
