# Generated by Django 3.2 on 2021-05-04 09:34

import citov.apps.news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_orders_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulations',
            name='upload',
            field=models.FileField(upload_to=citov.apps.news.models.content_GK, verbose_name='Pdf'),
        ),
    ]
